# GITHUB OVERRIDES
# can't change these
# safe: true
# lsi: false
# github: [Repository metadata]
source: '.'
exclude: ['node_modules', 'grunt', 'Gemfile', 'Gemfile.lock', 'package.json', '*.scss', '*.coffee','sarsite-2015']

# Build settings
markdown: kramdown
highlighter: pygments

# Site settings
title: 'Cowichan Search & Rescue'
email: 'info@cowichansar.org'
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cowsar.github.io" # the base hostname & protocol for your site


name: "Cowichan Search & Rescue"
tagline: "Professionally Trained Volunteers Dedicated To Bringing People Home. Anyone. Anytime. Anywhere."

address: 'PO Box 1034'
city: 'Duncan'
province: 'BC'
postal: 'V9L 3Y2'